// File generated by FlutterFire CLI (templated placeholder values).
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_on_signature_methods
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtYncYm8QxHwAMf9YuvtrWUhF6ne4sYgQ',
    appId: '1:226504199183:web:a0b12a3e366472f49ba77a',
    messagingSenderId: '226504199183',
    projectId: 'rahhal-ai',
    authDomain: 'rahhal-ai.firebaseapp.com',
    storageBucket: 'rahhal-ai.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr9siORxoU07nNVEwdop5355tdtu9y2yA',
    appId: '1:226504199183:android:dd40e93a4bd8b24f9ba77a',
    messagingSenderId: '226504199183',
    projectId: 'rahhal-ai',
    storageBucket: 'rahhal-ai.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpTvF5mTRiF4AKJsIi2egI2tjgnHr-8_s',
    appId: '1:226504199183:ios:6ca5168a4119816b9ba77a',
    messagingSenderId: '226504199183',
    projectId: 'rahhal-ai',
    storageBucket: 'rahhal-ai.firebasestorage.app',
    iosClientId: '226504199183-fnja9653ji7r7fhh5uett3u3hb0p0028.apps.googleusercontent.com',
    iosBundleId: 'com.rahhalai.rahhalFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtYncYm8QxHwAMf9YuvtrWUhF6ne4sYgQ',
    appId: '1:226504199183:web:3f18495cb8d13e669ba77a',
    messagingSenderId: '226504199183',
    projectId: 'rahhal-ai',
    authDomain: 'rahhal-ai.firebaseapp.com',
    storageBucket: 'rahhal-ai.firebasestorage.app',
  );
}
