#!/usr/bin/env node
/**
 * Generates rahhal_full_codebase.md — a single readable snapshot of the app's
 * source for sharing/review.
 *
 * Deliberately excludes .env (real API keys), build output, and dependency
 * folders. Run with: node tools/generate_codebase_md.js
 */
const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const ROOT = path.resolve(__dirname, '..');
const OUT = path.join(ROOT, 'rahhal_full_codebase.md');

// Files/dirs that must never end up in the dump.
const EXCLUDED_DIRS = new Set([
  'build', '.dart_tool', 'node_modules', '.git', '.idea', '.gradle',
  'ios', 'macos', 'windows', 'linux', 'web', 'test_driver',
]);
const EXCLUDED_FILES = new Set(['.env', 'rahhal_full_codebase.md']);

const LANG_BY_EXT = {
  '.dart': 'dart',
  '.js': 'javascript',
  '.json': 'json',
  '.yaml': 'yaml',
  '.yml': 'yaml',
  '.rules': 'javascript',
  '.gradle': 'groovy',
  '.kts': 'kotlin',
  '.xml': 'xml',
  '.md': 'markdown',
};

function walk(dir, acc = []) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.isDirectory()) {
      if (EXCLUDED_DIRS.has(entry.name)) continue;
      walk(path.join(dir, entry.name), acc);
    } else if (!EXCLUDED_FILES.has(entry.name)) {
      acc.push(path.join(dir, entry.name));
    }
  }
  return acc;
}

function rel(p) {
  return path.relative(ROOT, p).split(path.sep).join('/');
}

function sh(cmd, fallback = '') {
  try {
    return execSync(cmd, { cwd: ROOT, encoding: 'utf8' }).trim();
  } catch {
    return fallback;
  }
}

// ── Collect the files worth including ───────────────────────────────────────
const dartFiles = walk(path.join(ROOT, 'lib')).filter(f => f.endsWith('.dart')).sort();

const rootFiles = [
  'server.js',
  'pubspec.yaml',
  'firestore.rules',
  '.env.example',
  'README.md',
  'package.json',
].map(f => path.join(ROOT, f)).filter(fs.existsSync);

const androidFiles = [
  'android/app/build.gradle.kts',
  'android/build.gradle.kts',
  'android/gradle.properties',
  'android/app/src/main/AndroidManifest.xml',
].map(f => path.join(ROOT, f)).filter(fs.existsSync);

// ── Build the document ──────────────────────────────────────────────────────
const generatedAt = new Date().toISOString().slice(0, 10);
const branch = sh('git rev-parse --abbrev-ref HEAD', 'unknown');
const commit = sh('git rev-parse --short HEAD', 'unknown');
const recentCommits = sh('git log --oneline -15', '');

const out = [];
out.push('# رحّال AI — Full Codebase Snapshot');
out.push('');
out.push(`**Generated:** ${generatedAt}  `);
out.push(`**Branch:** \`${branch}\`  `);
out.push(`**Commit:** \`${commit}\``);
out.push('');
out.push('> Generated by `tools/generate_codebase_md.js`. Excludes `.env` (secrets),');
out.push('> build output, and dependency folders. Re-run the script to refresh.');
out.push('');
out.push('## Recent changes');
out.push('');
out.push('```');
out.push(recentCommits);
out.push('```');
out.push('');

// Table of contents
out.push('## Contents');
out.push('');
const sections = [
  ['Backend & configuration', [...rootFiles, ...androidFiles]],
  ['Flutter application (`lib/`)', dartFiles],
];
for (const [title, files] of sections) {
  out.push(`### ${title}`);
  out.push('');
  for (const f of files) out.push(`- \`${rel(f)}\``);
  out.push('');
}

// File bodies
for (const [title, files] of sections) {
  out.push('---');
  out.push('');
  out.push(`# ${title}`);
  out.push('');
  for (const f of files) {
    const ext = path.extname(f);
    const lang = LANG_BY_EXT[ext] || '';
    out.push(`## \`${rel(f)}\``);
    out.push('');
    out.push('```' + lang);
    out.push(fs.readFileSync(f, 'utf8').replace(/\s+$/, ''));
    out.push('```');
    out.push('');
  }
}

fs.writeFileSync(OUT, out.join('\n'), 'utf8');

const bytes = fs.statSync(OUT).size;
console.log(`Wrote ${rel(OUT)}`);
console.log(`  files: ${rootFiles.length + androidFiles.length + dartFiles.length}`);
console.log(`  size : ${(bytes / 1024).toFixed(0)} KB`);
